#!/usr/bin/env python3
"""Rasterizes assets/svg into LVGL images and renders the procedural artwork.

    uv run --with pillow --with numpy tools/gen_images.py

SVGs go through rsvg-convert at the exact on-screen size (no runtime scaling, so edges stay crisp).
Output: main/images/*.c (RGB565A8 for icons, RGB565 for opaque art) and main/images/images.h.
"""
import colorsys
import io
import math
import subprocess
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
SVG = ROOT / "assets" / "svg"
OUT = ROOT / "main" / "images"

# (svg path, sizes)
ICONS = {
    "hw/cpu": (28, 40), "hw/gpu": (28, 40), "hw/ram": (28, 40), "hw/ssd": (28, 40), "hw/net": (28, 40),
    "hw/temp": (22,), "hw/bolt": (22,), "hw/wifi": (28, 96), "hw/pc": (28, 40, 120),
    "brand/claude-color": (22, 36), "brand/codex-color": (22, 36), "brand/pi-color": (22, 36), "brand/omp-color": (22, 36), "brand/opencode-color": (22, 36),
    "fluent/bot_sparkle": (28, 40, 96), "fluent/checkmark_circle": (22, 32), "fluent/error_circle": (22, 32),
    "fluent/warning": (22, 32), "fluent/shield": (22, 32, 64), "fluent/question_circle": (22, 32, 64),
    "fluent/settings": (28, 40), "fluent/gauge": (28,), "fluent/clock": (22,), "fluent/link": (22,),
    "fluent/arrow_sync": (22,), "fluent/lightbulb_filament": (28,), "fluent/history": (22,),
    "fluent/toolbox": (28,), "fluent/code_block": (22,), "fluent/planet": (28,), "fluent/agents": (28, 40),
}


def ident(name):
    return name.replace("-color", "").replace("/", "_").replace("-", "_")


def rsvg(path, size):
    png = subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), str(path)],
                         check=True, capture_output=True).stdout
    return Image.open(io.BytesIO(png)).convert("RGBA")


def rgb565(rgb):
    r, g, b = (rgb[..., i].astype(np.uint16) for i in range(3))
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def dither(rgb):
    """Ordered dithering before RGB565 truncation: kills banding in the large gradients."""
    bayer = np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]], np.float32) / 16 - 0.5
    h, w = rgb.shape[:2]
    t = np.tile(bayer, (h // 4 + 1, w // 4 + 1))[:h, :w]
    out = rgb.astype(np.float32)
    out[..., 0] += t * 8
    out[..., 1] += t * 4
    out[..., 2] += t * 8
    return np.clip(out, 0, 255).astype(np.uint8)


def emit(name, img, alpha):
    w, h = img.size
    arr = np.asarray(img)
    px = rgb565(dither(arr[..., :3]) if not alpha else arr[..., :3]).astype("<u2").tobytes()
    data = px + (arr[..., 3].tobytes() if alpha else b"")
    cf = "LV_COLOR_FORMAT_RGB565A8" if alpha else "LV_COLOR_FORMAT_RGB565"
    lines = [data[i:i + 32] for i in range(0, len(data), 32)]
    body = ",\n".join(",".join(f"0x{b:02x}" for b in l) for l in lines)
    (OUT / f"{name}.c").write_text(
        f'#include "lvgl.h"\n// Generated by tools/gen_images.py\n'
        f"static const uint8_t map[] __attribute__((aligned(4))) = {{\n{body}\n}};\n"
        f"const lv_image_dsc_t {name} = {{\n"
        f"    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = {cf}, .w = {w}, .h = {h}, .stride = {w * 2}}},\n"
        f"    .data_size = sizeof(map),\n    .data = map,\n}};\n")
    return name


def lerp_colors(stops, t):
    """stops: [(pos, (r,g,b)), ...]; t: ndarray in [0,1]."""
    out = np.zeros(t.shape + (3,), np.float32)
    for (p0, c0), (p1, c1) in zip(stops, stops[1:]):
        m = (t >= p0) & (t <= p1)
        k = ((t - p0) / max(p1 - p0, 1e-6))[m][:, None]
        out[m] = np.array(c0) * (1 - k) + np.array(c1) * k
    return out


def hexc(s):
    s = s.lstrip("#")
    return tuple(int(s[i:i + 2], 16) for i in (0, 2, 4))


def ring(name, size, stops):
    """Conic gradient texture for an LVGL arc indicator spanning 135°→405° (clockwise from 3 o'clock)."""
    y, x = np.mgrid[0:size, 0:size].astype(np.float32) + 0.5
    ang = (np.degrees(np.arctan2(y - size / 2, x - size / 2)) - 135) % 360
    # The 90° gap below the gauge: its first half belongs to the end of the sweep, its second half
    # (just before the start) to the start, so rounded caps never pick up the other end's color.
    t = np.where(ang > 315, 0, np.clip(ang / 270, 0, 1))
    rgb = lerp_colors([(p, hexc(c)) for p, c in stops], t)
    img = Image.fromarray(np.dstack([rgb, np.full(t.shape, 255, np.float32)]).astype(np.uint8), "RGBA")
    return emit(name, img, False)


def hbar(name, w, h, stops):
    """Horizontal gradient texture for bars / sparklines."""
    t = np.tile(np.linspace(0, 1, w, dtype=np.float32), (h, 1))
    rgb = lerp_colors([(p, hexc(c)) for p, c in stops], t)
    img = Image.fromarray(np.dstack([rgb, np.full(t.shape, 255, np.float32)]).astype(np.uint8), "RGBA")
    return emit(name, img, False)


def aurora(name, w, h, base, blobs, grain=True):
    """Dark backdrop with soft colored light pools; blobs: [(cx, cy, radius, color, strength)]."""
    img = Image.new("RGB", (w, h), hexc(base))
    acc = np.asarray(img).astype(np.float32)
    y, x = np.mgrid[0:h, 0:w].astype(np.float32)
    for cx, cy, r, color, s in blobs:
        d = np.sqrt(((x - cx * w) / (r * w)) ** 2 + ((y - cy * h) / (r * w * 0.8)) ** 2)
        k = np.exp(-d * d * 2.2) * s
        acc += k[..., None] * (np.array(hexc(color), np.float32) - acc) * 0.9
    # vignette
    v = np.sqrt(((x / w) - 0.5) ** 2 * 1.2 + ((y / h) - 0.5) ** 2)
    acc *= (1 - np.clip(v - 0.35, 0, 1) * 0.55)[..., None]
    if grain:
        acc += np.random.default_rng(7).normal(0, 1.2, acc.shape[:2])[..., None]
    rgba = np.dstack([np.clip(acc, 0, 255), np.full((h, w), 255)]).astype(np.uint8)
    return emit(name, Image.fromarray(rgba, "RGBA"), False)


def glow(name, size, color):
    """Soft round glow (alpha only matters) used behind status icons and the idle-screen hero."""
    img = Image.new("RGBA", (size, size), hexc(color) + (0,))
    a = Image.new("L", (size, size), 0)
    ImageDraw.Draw(a).ellipse([size * .2, size * .2, size * .8, size * .8], fill=200)
    a = a.filter(ImageFilter.GaussianBlur(size * .12))
    img.putalpha(a)
    return emit(name, img, True)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for f in OUT.glob("*.c"):
        f.unlink()
    names = []
    for svg, sizes in ICONS.items():
        for s in sizes:
            names.append(emit(f"img_{ident(svg)}_{s}", rsvg(SVG / f"{svg}.svg", s), True))

    # Gauge sweeps: cool → hot so the color itself reads as load.
    names.append(ring("img_ring_cpu", 184, [(0, "#22d3ee"), (.45, "#6366f1"), (.75, "#a855f7"), (1, "#f43f5e")]))
    names.append(ring("img_ring_gpu", 184, [(0, "#34d399"), (.45, "#10b981"), (.75, "#eab308"), (1, "#f97316")]))
    names.append(ring("img_ring_small", 120, [(0, "#38bdf8"), (.5, "#818cf8"), (1, "#e879f9")]))
    names.append(hbar("img_bar_ram", 256, 12, [(0, "#22d3ee"), (1, "#3b82f6")]))
    names.append(hbar("img_bar_vram", 256, 12, [(0, "#34d399"), (1, "#14b8a6")]))
    names.append(hbar("img_bar_disk", 256, 12, [(0, "#fb7185"), (1, "#e11d48")]))
    names.append(hbar("img_bar_ctx", 256, 12, [(0, "#a78bfa"), (.7, "#f472b6"), (1, "#fb923c")]))

    # Full-screen backdrops are rendered on the device (ui/bg.c) so they can follow the accent color.
    names.append(glow("img_glow_amber", 160, "#f59e0b"))
    names.append(glow("img_glow_accent", 320, "#6366f1"))

    (OUT / "images.h").write_text("#pragma once\n#include \"lvgl.h\"\n// Generated by tools/gen_images.py\n" +
                                  "".join(f"LV_IMAGE_DECLARE({n});\n" for n in names))
    total = sum(f.stat().st_size for f in OUT.glob("*.c"))
    print(f"{len(names)} images, {total / 1e6:.1f} MB of C source")


if __name__ == "__main__":
    main()
