#!/usr/bin/env bash
# Regenerates main/fonts/*.c and main/fonts/icons.h from Inter, JetBrains Mono and Material Symbols.
# Source fonts are downloaded once into tools/.fontcache.
set -euo pipefail
cd "$(dirname "$0")/.."
C=tools/.fontcache; O=main/fonts
mkdir -p "$C" "$O"

if [ ! -f "$C/Inter-Medium.ttf" ]; then
  url=$(curl -s https://api.github.com/repos/rsms/inter/releases/latest | jq -r '.assets[0].browser_download_url')
  curl -sL -o "$C/inter.zip" "$url"
  unzip -qjo "$C/inter.zip" 'extras/ttf/Inter-Medium.ttf' 'extras/ttf/Inter-SemiBold.ttf' 'extras/ttf/Inter-Bold.ttf' -d "$C"
fi
if [ ! -f "$C/JetBrainsMono-SemiBold.ttf" ]; then
  url=$(curl -s https://api.github.com/repos/JetBrains/JetBrainsMono/releases/latest | jq -r '.assets[] | select(.name|endswith(".zip")) | .browser_download_url' | head -1)
  curl -sL -o "$C/jbm.zip" "$url"
  unzip -qjo "$C/jbm.zip" 'fonts/ttf/JetBrainsMono-Medium.ttf' 'fonts/ttf/JetBrainsMono-SemiBold.ttf' -d "$C"
fi
if [ ! -f "$C/SourceSerif4-Semibold.ttf" ]; then  # Newsprint theme
  url=$(curl -s https://api.github.com/repos/adobe-fonts/source-serif/releases/latest | jq -r '.assets[] | select(.name|test("Desktop")) | .browser_download_url' | head -1)
  curl -sL -o "$C/ss.zip" "$url"
  unzip -qjo "$C/ss.zip" '*/TTF/SourceSerif4-Semibold.ttf' '*/TTF/SourceSerif4Display-Semibold.ttf' -d "$C"
fi
if [ ! -f "$C/IBMPlexSans-Light.ttf" ]; then  # Paper / Ink themes
  curl -sL -o "$C/plexsans.zip" 'https://github.com/IBM/plex/releases/download/%40ibm/plex-sans%401.1.0/ibm-plex-sans.zip'
  curl -sL -o "$C/plexmono.zip" 'https://github.com/IBM/plex/releases/download/%40ibm/plex-mono%402.5.0/ibm-plex-mono.zip'
  for w in Thin Light Regular Medium SemiBold; do unzip -qjo "$C/plexsans.zip" "*/ttf/IBMPlexSans-$w.ttf" -d "$C"; done
  unzip -qjo "$C/plexmono.zip" '*/ttf/IBMPlexMono-Regular.ttf' -d "$C"
fi
if [ ! -f "$C/JetBrainsMonoNerdFont-Regular.ttf" ]; then  # fastfetch's icons (system info popup)
  if [ -f /usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf ]; then
    cp /usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf "$C/"
  else
    curl -sL -o "$C/jbmnf.zip" https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
    unzip -qjo "$C/jbmnf.zip" 'JetBrainsMonoNerdFont-Regular.ttf' -d "$C"
  fi
fi
SYM="$C/MaterialSymbolsRounded.ttf"
if [ ! -f "$SYM" ]; then
  base='https://github.com/google/material-design-icons/raw/master/variablefont/MaterialSymbolsRounded%5BFILL,GRAD,opsz,wght%5D'
  curl -sL -o "$SYM" "$base.ttf"
  curl -sL -o "$C/MaterialSymbolsRounded.codepoints" "$base.codepoints"
fi

# Latin-1 plus the typographic punctuation and arrows agents like to emit.
TEXT='0x20-0x7E,0xA0-0xFF,0x2013-0x2014,0x2018-0x201D,0x2022,0x2026,0x2190-0x2193,0x2212,0x2713,0x2717,0x00B7'
SERIF_TEXT='0x20-0x7E,0xA0-0xFF,0x2013-0x2014,0x2018-0x201D,0x2022,0x2026,0x2212'
DIGITS='0x20,0x25,0x2B-0x3A,0x41-0x5A,0x61-0x7A,0xB0'

# icon name -> C identifier
ICONS=(memory:CPU developer_board:GPU storage:STORAGE hard_drive:DISK lan:LAN wifi:WIFI wifi_off:WIFI_OFF
  settings:SETTINGS smart_toy:AGENT terminal:TERMINAL check_circle:DONE error:ERROR help:QUESTION shield:PERMISSION
  pause_circle:IDLE progress_activity:WORKING computer:PC desktop_windows:DESKTOP devices:DEVICES swap_horiz:SWAP
  brightness_6:BRIGHTNESS palette:PALETTE thermostat:TEMP bolt:POWER speed:SPEED schedule:CLOCK
  arrow_downward:DOWN arrow_upward:UP system_update:UPDATE restart_alt:RESTART link:LINK link_off:LINK_OFF
  close:CLOSE chevron_right:RIGHT chevron_left:LEFT info:INFO delete:DELETE push_pin:PIN notifications:BELL
  timer:TIMER language:GLOBE code:CODE folder:FOLDER build:BUILD dns:SERVER data_usage:DATA tune:TUNE
  visibility:EYE power_settings_new:POWER_OFF key:KEY hourglass_top:HOURGLASS forum:CHAT account_tree:TREE
  monitor_heart:PULSE sensors:SENSORS light_mode:SUN expand_more:EXPAND person:USER mode_fan:FAN layers:LAYERS swap_vert:SWAPV apps:APPS memory_alt:RAM music_note:MUSIC sports_esports:GAME folder_open:FOLDER_OPEN)
codes=(); { echo '#pragma once'; echo '// Generated by tools/gen_fonts.sh: Material Symbols Rounded glyphs (UTF-8).'; } > "$O/icons.h"
for pair in "${ICONS[@]}"; do
  name=${pair%%:*}; id=${pair##*:}
  cp=$(grep -m1 "^$name " "$C/MaterialSymbolsRounded.codepoints" | cut -d' ' -f2)
  [ -n "$cp" ] || { echo "missing icon $name" >&2; exit 1; }
  codes+=("0x$cp")
  utf8=$(printf "\\u$cp" | od -An -tx1 | tr -d ' \n' | sed 's/../\\x&/g')
  echo "#define ICON_$id \"$utf8\"" >> "$O/icons.h"
done
ICON_RANGE=$(IFS=,; echo "${codes[*]}")

conv() { # name size font range [bpp]
  npx -y lv_font_conv --no-compress --format lvgl --bpp "${5:-4}" --size "$2" --font "$3" -r "$4" \
    --lv-include lvgl.h -o "$O/$1.c" --lv-font-name "$1"
}
for s in 14 16 18 20 24; do conv inter_${s} $s "$C/Inter-Medium.ttf" "$TEXT"; done
for s in 16 18 20 24 28 36; do conv inter_semi_${s} $s "$C/Inter-SemiBold.ttf" "$TEXT"; done  # 16-24: markdown bold
conv inter_bold_56 56 "$C/Inter-Bold.ttf" "$DIGITS"
conv inter_bold_140 140 "$C/Inter-Bold.ttf" '0x20,0x30-0x3A'
for s in 14 16 18; do conv mono_${s} $s "$C/JetBrainsMono-Medium.ttf" "$TEXT"; done
for s in 24 32 44; do conv mono_semi_${s} $s "$C/JetBrainsMono-SemiBold.ttf" "$DIGITS"; done
# Newsprint: serif headlines and figures
for s in 18 22 28; do conv serif_${s} $s "$C/SourceSerif4-Semibold.ttf" "$SERIF_TEXT"; done
conv serif_36 36 "$C/SourceSerif4Display-Semibold.ttf" "$SERIF_TEXT"
for s in 26 44; do conv serif_num_${s} $s "$C/SourceSerif4Display-Semibold.ttf" "$DIGITS"; done
conv serif_num_140 140 "$C/SourceSerif4Display-Semibold.ttf" '0x20,0x30-0x3A'
# Paper / Ink: IBM Plex. Its figures are tabular by default, so changing numbers don't jiggle.
PLEX_TEXT="$SERIF_TEXT,0x2190-0x2193"
for s in 14 16 18; do conv plex_${s} $s "$C/IBMPlexSans-Regular.ttf" "$PLEX_TEXT"; done
for s in 18 20 22; do conv plex_med_${s} $s "$C/IBMPlexSans-Medium.ttf" "$PLEX_TEXT"; done
for s in 15 16 18 20 22 28; do conv plex_semi_${s} $s "$C/IBMPlexSans-SemiBold.ttf" "$PLEX_TEXT"; done  # 16/20: markdown bold
conv plex_light_36 36 "$C/IBMPlexSans-Light.ttf" "$PLEX_TEXT"
for s in 30 56; do conv plex_light_num_${s} $s "$C/IBMPlexSans-Light.ttf" "$DIGITS"; done
conv plex_thin_140 140 "$C/IBMPlexSans-Thin.ttf" '0x20,0x30-0x3A'
for s in 14 16; do conv plex_mono_${s} $s "$C/IBMPlexMono-Regular.ttf" "$PLEX_TEXT"; done
for s in 18 22 28 40 64; do conv icons_${s} $s "$SYM" "$ICON_RANGE"; done
# Nerd Font icons fastfetch prints: its presets' icons, Omarchy's, common defaults, distro logos.
NF='0xe23c,0xe266,0xe621,0xe627,0xe659,0xe6a9,0xe712,0xe795,0xe7a3,0xe7a8,0xe900,0xeab0,0xeb29,0xed0d,0xee00-0xee05,0xefc5,0xefcc,0xf007,0xf013,0xf017,0xf028,0xf031,0xf0a0,0xf108,0xf109,0xf11b,0xf120,0xf178,0xf17c,0xf187,0xf192,0xf1ab,0xf1eb,0xf1fc,0xf242,0xf293,0xf2d0,0xf2db,0xf300-0xf381,0xf43a,0xf488,0xf489,0xf492,0xf4bc,0xf003b,0xf0079,0xf00de,0xf0150,0xf01c4,0xf01c5,0xf0249,0xf027c,0xf02a2,0xf02ca,0xf0322,0xf035b,0xf0379,0xf03d6,0xf03d8,0xf046d,0xf04e1,0xf052b,0xf057e,0xf075a,0xf08ae,0xf0928,0xf0960,0xf09e8,0xf0a5f,0xf0a60,0xf0e09,0xf0e0c,0xf0ee0,0xf1104,0xf199f,0xf1ad0'
conv nf_22 22 "$C/JetBrainsMonoNerdFont-Regular.ttf" "$NF"

{ echo '#pragma once'; echo '#include "lvgl.h"'; echo '#include "icons.h"'
  for f in "$O"/*.c; do echo "LV_FONT_DECLARE($(basename "$f" .c))"; done; } > "$O/fonts.h"
echo "generated $(ls "$O"/*.c | wc -l) fonts"
